/**
 * Cloudflare Worker — Edge Router
 *
 * Routes:
 *   /ca/*       → Decoupled CMS (Next.js on Vercel)
 *   /_next/*    → Next.js static assets (JS, CSS, images)
 *   /api/*      → Decoupled CMS API (webhook endpoint)
 *   Everything  → WordPress origin
 */

const CMS_ORIGIN = "https://your-app.vercel.app"; // Replace with actual Vercel deployment URL
const WP_ORIGIN = "https://example.com";           // Replace with actual WordPress domain

function shouldRouteToCMS(path) {
  // Strict /ca/ prefix — requires the trailing slash so paths like
  // /california-funding or /careers stay on WordPress
  if (path === "/ca" || path.startsWith("/ca/")) return true;

  // Next.js static assets — JS bundles, CSS, images generated by the build.
  // Without this, /ca/* pages lose their styles because the browser fetches
  // /_next/static/... which would otherwise fall through to WordPress.
  if (path.startsWith("/_next/")) return true;

  // Webhook and revalidation API endpoints
  if (path.startsWith("/api/webhook") || path.startsWith("/api/revalidate")) return true;

  return false;
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname;

    if (shouldRouteToCMS(path)) {
      const cmsUrl = new URL(path + url.search, CMS_ORIGIN);
      const cmsReq = new Request(cmsUrl.toString(), {
        method: request.method,
        headers: request.headers,
        body: request.method !== "GET" ? request.body : undefined,
      });

      const response = await fetch(cmsReq);

      const headers = new Headers(response.headers);
      headers.set("X-Routed-Via", "cloudflare-worker");
      headers.set("X-Origin", "decoupled-cms");

      return new Response(response.body, {
        status: response.status,
        headers,
      });
    }

    // Default: proxy to WordPress
    const wpUrl = new URL(path + url.search, WP_ORIGIN);
    const wpReq = new Request(wpUrl.toString(), {
      method: request.method,
      headers: request.headers,
      body: request.method !== "GET" ? request.body : undefined,
    });

    const wpResponse = await fetch(wpReq);

    const headers = new Headers(wpResponse.headers);
    headers.set("X-Routed-Via", "cloudflare-worker");
    headers.set("X-Origin", "wordpress");

    return new Response(wpResponse.body, {
      status: wpResponse.status,
      headers,
    });
  },
};
